# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=True)),
                ('char', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('float', models.FloatField()),
                ('integer', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.TimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
