# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel1',
            name='choices1',
            field=models.CharField(choices=[('A', 'Alpha'), ('B', 'Beta')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
